symfonycasts_verify_email:
  lifetime: 3600 # Durée de vie du lien de vérification en secondes (1 heure par défaut)
  signature_algorithm: sha256 # Algorithme de signature utilisé pour générer le lien de vérification
